version: "0.1"

services:
  db:
    image: "postgres:latest"
    container_name: "postgres-db"
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=123"
      - "POSTGRES_DB=db"
    ports:
      - 13000:5432
  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: "pgadmin"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@info.com"
      - "PGADMIN_DEFAULT_PASSWORD=common"
      - "PGADMIN_DISABLE_POSTFIX=true"
      - "PGADMIN_LISTENING_PORT=80"
    ports:
      - 7799:80