name: Get secret value
on: push
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Set up secret file
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo $JWT_SECRET >> secrets.txt