name: Hide Secret Info
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::${{ secrets.JWT_SECRET }}"
      - name: Echo JWT secret
        run: echo "JWT secret = ${{ secrets.JWT_SECRET }}"